spring.application.name=juris
server.servlet.context-path=/juris

# H2
# PC jdbc:h2:file:C:/Users/nanda/db_processos
# SEMAS jdbc:h2:file:C:/Users/fernanda.genu/.vscode/BancoH2
spring.datasource.url=jdbc:h2:file:C:/Users/nanda/BancoH2
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# IMPORTANT: do NOT drop tables on restart
spring.jpa.hibernate.ddl-auto=update

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Swagger
springdoc.api-docs.path=/api-docs

# Security
api.security.token.value=${JWT_SECRET:secret-key}

# JPA
spring.jpa.defer-datasource-initialization=true

# Flyway
spring.flyway.enabled=false

# Logs
logging.level.org.springframework.security=DEBUG
server.error.include-stacktrace=never

server.port=9000